// Generated by CoffeeScript 1.3.3
(function() {
  var app, cells, express, get_cell_data, get_cell_value, io, last_cell_id, next_cell_id, server, set_cell_data, set_cell_value;

  io = require('socket.io');

  express = require('express');

  app = express();

  server = app.listen(8080);

  app.use(express["static"](__dirname + '/'));

  io = io.listen(server);

  last_cell_id = 0;

  next_cell_id = function() {
    last_cell_id += 1;
    return last_cell_id;
  };

  cells = {};

  set_cell_value = function(id, key, value, emit, callback) {
    var cell, old_value;
    if (emit == null) {
      emit = true;
    }
    if (!id) {
      id = next_cell_id();
    }
    cell = cells[id] != null ? cells[id] : function() {
      cells[id] = {};
      return cells[id];
    };
    old_value = cell[key];
    cell[key] = value;
    if (emit) {
      cells.emit('set_cell_value', {
        id: id,
        key: key,
        old_value: old_value,
        new_value: value
      });
    }
    return callback(id, key, value, old_value);
  };

  set_cell_data = function(id, data, callback) {
    var count, key, len, old_values, value,
      _this = this;
    count = 0;
    len = data.length;
    old_values = {};
    for (key in data) {
      value = data[key];
      set_cell_value(key, value, false, function(_id, key, value, old_value) {
        if (!id) {
          id = _id;
        }
        count += 1;
        old_values[key] = old_value;
        if (count === len) {
          return cells.emit('set_cell_data', {
            id: id,
            old_values: old_values,
            new_values: data
          });
        }
      });
    }
    if (data.length === 0) {
      cells[id] = {};
    }
    return callback(id, data);
  };

  get_cell_data = function(id, callback) {
    return callback(id, cells.id || {});
  };

  get_cell_value = function(id, key, callback) {
    var _ref;
    return callback(id, cells != null ? (_ref = cells.id) != null ? _ref.key : void 0 : void 0);
  };

  io.sockets.on('connection', function(socket) {
    socket.on('set_cell_value', function(data) {
      var _this = this;
      return set_cell_value(data.id, data.key, data.value, function(id, key, value, old_value) {
        return socket.emit('set_cell_value', {
          success: true,
          id: id,
          key: key,
          value: value,
          token: data != null ? data.token : void 0
        });
      });
    });
    socket.on('set_cell_data', function(data) {
      var _this = this;
      return set_cell_data(data.id, data.data, function(id, data, old_data) {
        return socket.emit('set_cell_data', {
          success: true,
          id: id,
          data: data,
          old_data: old_data,
          token: data != null ? data.token : void 0
        });
      });
    });
    socket.on('get_cell_value', function(data) {
      var _this = this;
      return get_cell_value(data.id, data.key, function(id, value) {
        return socket.emit('get_cell_value', {
          success: true,
          id: id,
          key: key,
          value: value,
          token: data != null ? data.token : void 0
        });
      });
    });
    return socket.on('get_cell_data', function(data) {
      var _this = this;
      return get_cell_data(data.id, function(id, data) {
        return socket.emit('get_cell_data', {
          success: true,
          id: id,
          data: data,
          token: data != null ? data.token : void 0
        });
      });
    });
  });

}).call(this);
