// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['spine'], function(spine) {
    var Cell;
    return Cell = (function(_super) {

      __extends(Cell, _super);

      Cell.extend(Spine.Events);

      function Cell(id) {
        this.id = id;
        this.data = {};
        this.tokens = {};
      }

      Cell.prototype._new_token_id = function() {
        return new Date().getTime();
      };

      Cell.prototype.set = function(key, value, token, fire) {
        if (fire == null) {
          fire = true;
        }
        console.log("cell [set] " + key + " " + value + " " + token + " " + fire);
        this.data[key] = value;
        if (!((token != null) || token > this.tokens[key])) {
          return;
        }
        token = this.tokens[key] = this._new_token_id();
        if (fire) {
          console.log("cells firing set_cell_value");
          return this.trigger('set_cell_value', {
            key: key,
            value: value,
            token: token
          });
        }
      };

      Cell.prototype.get = function(key) {
        return this.data[key];
      };

      Cell.prototype.set_data = function(data) {
        var k, token, v;
        if (!(data != null ? data.length : void 0)) {
          return;
        }
        token = this._new_token_id();
        for (k in data) {
          v = data[k];
          this.set(k, v, token, false);
        }
        return this.trigger('set_cell_data', {
          id: this.id,
          data: data,
          token: token
        });
      };

      Cell.prototype.clear = function() {
        return this.set_data({});
      };

      return Cell;

    })(Spine.Module);
  });

}).call(this);
