// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var last_cell_id;
    last_cell_id = 0;
    return {
      fire_set_value: function(to_obj, id, key, value, token) {
        return to_obj.fire('cell:set_value', {
          id: id,
          key: key,
          value: value,
          token: token
        });
      },
      fire_set_data: function(to_obj, id, data, token) {
        return to_obj.fire('cell:set_data', {
          id: id,
          data: data,
          token: token
        });
      },
      new_cell_id: function() {
        return last_cell_id += 1;
      },
      new_token_id: function() {
        return '' + (new Date().getTime()) + (this.id || '');
      }
    };
  });

}).call(this);
