// Generated by CoffeeScript 1.3.3
(function() {

  define(['mediator', 'tracker'], function(mediator, tracker) {
    var cells_id_tracker, setup_cell,
      _this = this;
    cells_id_tracker = new Tracker();
    setup_cell = function(data) {
      var cell;
      if (!(cell_id_tracker.first(data.id) || !(data.id != null))) {
        cell = new Cell(data);
        return cells_id_tracker.track(cell.id, cell);
      }
    };
    mediator.on('cell:init', setup_cell);
    mediator.on('cell:set_value', setup_cell);
    mediator.on('cell:set_data', setup_cell);
    return cells_id_tracker;
  });

}).call(this);
