// Generated by CoffeeScript 1.3.3
(function() {

  define(['mediator', 'cell_id_tracker'], function(mediator, cell_id_tracker) {
    var fire_cell_state,
      _this = this;
    fire_cell_state = function(to_obj, id) {
      var cell;
      cell = cell_id_tracker.first(id);
      if (cell != null) {
        return to_obj.fire('cell:set_data', {
          id: id,
          token: 0,
          data: cell.get_data()
        });
      }
    };
    return meditor.on('cell:init', function(data) {
      return fire_cell_state(data.__connection, id);
    });
  });

}).call(this);
