// Generated by CoffeeScript 1.3.3
(function() {

  define(['mediator', 'cell_id_tracker'], function(mediator, cell_id_tracker) {
    var fire_cell_state,
      _this = this;
    fire_cell_state = function(to_obj, id) {
      var cell, k, v, _ref, _results;
      cell = cell_id_tracker.first(id);
      if (cell != null) {
        _ref = cell.get_data();
        _results = [];
        for (k in _ref) {
          v = _ref[k];
          _results.push(cell.fire_set_data(to_obj, id, key, value, cell.tokens[k]));
        }
        return _results;
      }
    };
    return meditor.on('cell:init', function(data) {
      return fire_cell_state(data.__connection, id);
    });
  });

}).call(this);
