// Generated by CoffeeScript 1.3.3
(function() {

  define(['socketio_handler'](function() {
    var _this = this;
    return {
      add_socketio_connection: function(socketio_connection) {
        return socketio_handler(socketio_connection);
      }
    };
  }));

}).call(this);
