// Generated by CoffeeScript 1.3.3
(function() {

  define(['socketio_handler'], function(socketio_handler) {
    return {
      add_socketio_server: socketio_handler.handle_server,
      add_socketio_socket: socketio_handler.handle_socket
    };
  });

}).call(this);
