// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      spine: {
        deps: [],
        exports: 'Spine'
      }
    }
  });

  requirejs([], function() {});

}).call(this);
