// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      spine: {
        deps: [],
        exports: 'Spine'
      }
    }
  });

  requirejs(['overrides', 'mediator', 'spine', 'cell'], function(overrides, mediator, spine, cell) {
    return this.app = {
      overrides: overrides,
      mediator: mediator,
      spine: spine,
      cell: cell
    };
  });

}).call(this);
