// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      spine: {
        exports: 'Spine'
      },
      "socket.io": {
        exports: 'io'
      }
    },
    paths: {
      "socket.io": '/socket.io/socket.io.js'
    }
  });

  requirejs(['overrides', 'socket.io', 'liverest', 'cell'], function(overries, io, liverest, Cell) {
    var socket;
    this.app = {
      io: io,
      liverest: liverest,
      cell: Cell
    };
    socket = io.connect('http://localhost');
    return liverest.add_socketio_socket(socket);
  });

}).call(this);
