// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cell'], function(Cell) {
    var MemoryCell;
    return MemoryCell = (function(_super) {

      __extends(MemoryCell, _super);

      function MemoryCell() {
        this.data = {};
        MemoryCell.__super__.constructor.call(this, arguments);
      }

      MemoryCell.prototype._set = function(key, value, callback) {
        if (callback == null) {
          callback = function() {};
        }
        this.data[key] = value;
        return callback(true, key, value);
      };

      return MemoryCell;

    })(Cell);
  });

}).call(this);
