// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(function() {
    return function(io_server) {
      var _this = this;
      mediator.instance_extend(socket);
      socket.on((function(e, d, r) {
        return r(true);
      }), mediator.fire);
      return mediator.on(function(event, data, r) {
        if (data.id) {
          return socket.get('tracking_cells', function(err, cells) {
            var _ref;
            return r(true)((_ref = data.id, __indexOf.call(cells || [], _ref) >= 0) ? void 0 : r(false));
          });
        } else {
          return r(false);
        }
      }, function(event, event_data) {
        event_data.__connection = socket;
        return socket.fire(event, event_data);
      });
    };
  });

}).call(this);
