// Generated by CoffeeScript 1.3.3
(function() {

  define(['mediator', 'tracker'], function(mediator, tracker) {
    var add_tracking, socket_cell_tracker,
      _this = this;
    socket_cell_tracker = new Tracker();
    add_tracking = function(event_data) {
      if (event_data.__source && event_data.id) {
        return socket_cell_tracker.track(event_data.id, event_data.__source);
      }
    };
    mediator.on('cell:set_value', add_tracking);
    mediator.on('cell:set_data', add_tracking);
    mediator.on('cell:init', add_tracking);
    return socket_cell_tracker;
  });

}).call(this);
